/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JOptionPane;
import server.ServerNit;

/**
 *
 * @author Jovana
 */
public class ServerskaForma extends javax.swing.JFrame {
    private ServerNit nitServer;
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        lblStatus.setText("Server je ugasen!");
        btnPokreni1.setEnabled(true);
        btnZaustavi.setEnabled(false);
        setTitle("Serverska Forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        btnZaustavi = new javax.swing.JButton();
        btnPokreni1 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKB = new javax.swing.JMenu();
        menuItemIzmeniKonf = new javax.swing.JMenuItem();
        itemPort = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl.setText("Server status:");

        btnZaustavi.setText("Zaustavi Server");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        btnPokreni1.setText("Pokreni Server");
        btnPokreni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreni1ActionPerformed(evt);
            }
        });

        lblStatus.setText("Server status:");

        menuKB.setText("Konfiguracija baze");

        menuItemIzmeniKonf.setText("izmeni konfiguraciju");
        menuItemIzmeniKonf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIzmeniKonfActionPerformed(evt);
            }
        });
        menuKB.add(menuItemIzmeniKonf);

        itemPort.setText("izmeni port");
        itemPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPortActionPerformed(evt);
            }
        });
        menuKB.add(itemPort);

        jMenuBar1.add(menuKB);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(btnPokreni1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(lblStatus))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZaustavi)
                    .addComponent(btnPokreni1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemIzmeniKonfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIzmeniKonfActionPerformed
        new KonfiguracijaBaze(this, false).setVisible(true);
    }//GEN-LAST:event_menuItemIzmeniKonfActionPerformed

    private void btnPokreni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreni1ActionPerformed
        if(nitServer==null || !nitServer.isAlive()){
            nitServer=new ServerNit();
            nitServer.start();
            lblStatus.setText("Server je pokrenut!");
            btnZaustavi.setEnabled(true);
            btnPokreni1.setEnabled(false);
           
        }
    }//GEN-LAST:event_btnPokreni1ActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        if(nitServer.getServerSocket()!=null && nitServer.getServerSocket().isBound()){
            try {
                nitServer.getServerSocket().close();
                JOptionPane.showMessageDialog(null, "Server je ugasen, gasenje programa");
                this.dispose();
                System.exit(0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void itemPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPortActionPerformed
        new KonfiguracijaPorta(this, false).setVisible(true);
    }//GEN-LAST:event_itemPortActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni1;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JMenuItem itemPort;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuItem menuItemIzmeniKonf;
    private javax.swing.JMenu menuKB;
    // End of variables declaration//GEN-END:variables
}
