/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

/**
 *
 * @author Jovana
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Glavna Forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProdavac = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKorisni = new javax.swing.JMenu();
        menuItemKorisnikKreiraj = new javax.swing.JMenuItem();
        menuItemPrikaziKorisnik = new javax.swing.JMenuItem();
        menuKartaPredstave = new javax.swing.JMenu();
        menuItemKrerirajKartPredstava = new javax.swing.JMenuItem();
        menuItemPrikaziKarty = new javax.swing.JMenuItem();
        menuProdavac = new javax.swing.JMenu();
        menuItemPrikaziProdavac = new javax.swing.JMenuItem();
        menuItemKreirajProdavac = new javax.swing.JMenuItem();
        menuMesto = new javax.swing.JMenu();
        menuItemKreirajMesto = new javax.swing.JMenuItem();
        menuItemPrikaziMesta = new javax.swing.JMenuItem();
        menuSmena = new javax.swing.JMenu();
        menuItemUbaciSmena = new javax.swing.JMenuItem();
        menuItemPrikaziSmene = new javax.swing.JMenuItem();
        menuRacun = new javax.swing.JMenu();
        menuItemPrikaziRacun = new javax.swing.JMenuItem();
        menuItemKreirajRacun = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dobrodosli");

        lblProdavac.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(lblProdavac)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblProdavac))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        menuKorisni.setText("Korisnik");

        menuItemKorisnikKreiraj.setText("Kreiraj Korisnik");
        menuItemKorisnikKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKorisnikKreirajActionPerformed(evt);
            }
        });
        menuKorisni.add(menuItemKorisnikKreiraj);

        menuItemPrikaziKorisnik.setText("Prikazi Korisnik");
        menuItemPrikaziKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikaziKorisnikActionPerformed(evt);
            }
        });
        menuKorisni.add(menuItemPrikaziKorisnik);

        jMenuBar1.add(menuKorisni);

        menuKartaPredstave.setText("Karta Predstave");

        menuItemKrerirajKartPredstava.setText("Kreiraj Kartu");
        menuItemKrerirajKartPredstava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKrerirajKartPredstavaActionPerformed(evt);
            }
        });
        menuKartaPredstave.add(menuItemKrerirajKartPredstava);

        menuItemPrikaziKarty.setText("Prikazi");
        menuItemPrikaziKarty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikaziKartyActionPerformed(evt);
            }
        });
        menuKartaPredstave.add(menuItemPrikaziKarty);

        jMenuBar1.add(menuKartaPredstave);

        menuProdavac.setText("Prodavac");

        menuItemPrikaziProdavac.setText("Prikazi prodavac");
        menuItemPrikaziProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikaziProdavacActionPerformed(evt);
            }
        });
        menuProdavac.add(menuItemPrikaziProdavac);

        menuItemKreirajProdavac.setText("Kreiraj prodavca");
        menuItemKreirajProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKreirajProdavacActionPerformed(evt);
            }
        });
        menuProdavac.add(menuItemKreirajProdavac);

        jMenuBar1.add(menuProdavac);

        menuMesto.setText("Mesto");

        menuItemKreirajMesto.setText("Kreiraj Mesto");
        menuItemKreirajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKreirajMestoActionPerformed(evt);
            }
        });
        menuMesto.add(menuItemKreirajMesto);

        menuItemPrikaziMesta.setText("Prikazi Mesta");
        menuItemPrikaziMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikaziMestaActionPerformed(evt);
            }
        });
        menuMesto.add(menuItemPrikaziMesta);

        jMenuBar1.add(menuMesto);

        menuSmena.setText("Smena");

        menuItemUbaciSmena.setText("Ubaci Smenu");
        menuItemUbaciSmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUbaciSmenaActionPerformed(evt);
            }
        });
        menuSmena.add(menuItemUbaciSmena);

        menuItemPrikaziSmene.setText("Prikazi Smenu");
        menuItemPrikaziSmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikaziSmeneActionPerformed(evt);
            }
        });
        menuSmena.add(menuItemPrikaziSmene);

        jMenuBar1.add(menuSmena);

        menuRacun.setText("Racun");

        menuItemPrikaziRacun.setText("Prikazi Racun");
        menuItemPrikaziRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikaziRacunActionPerformed(evt);
            }
        });
        menuRacun.add(menuItemPrikaziRacun);

        menuItemKreirajRacun.setText("Kreiraj racun");
        menuItemKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKreirajRacunActionPerformed(evt);
            }
        });
        menuRacun.add(menuItemKreirajRacun);

        jMenuBar1.add(menuRacun);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPrikaziKartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikaziKartyActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikaziKarteFormu();
    }//GEN-LAST:event_menuItemPrikaziKartyActionPerformed

    private void menuItemPrikaziKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikaziKorisnikActionPerformed
       cordinator.Cordinator.getInstance().otvoriPrikazPacijenataFormu();
    }//GEN-LAST:event_menuItemPrikaziKorisnikActionPerformed

    private void menuItemKorisnikKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKorisnikKreirajActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajKorisnikaFormu();
    }//GEN-LAST:event_menuItemKorisnikKreirajActionPerformed

    private void menuItemKreirajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKreirajMestoActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajMestoFormu();
    }//GEN-LAST:event_menuItemKreirajMestoActionPerformed

    private void menuItemPrikaziMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikaziMestaActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikaziMestaFormu();
    }//GEN-LAST:event_menuItemPrikaziMestaActionPerformed

    private void menuItemKrerirajKartPredstavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKrerirajKartPredstavaActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajKartuFormu();
    }//GEN-LAST:event_menuItemKrerirajKartPredstavaActionPerformed

    private void menuItemUbaciSmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUbaciSmenaActionPerformed
         cordinator.Cordinator.getInstance().otvoriUbaciSmenaFormu();
    }//GEN-LAST:event_menuItemUbaciSmenaActionPerformed

    private void menuItemPrikaziSmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikaziSmeneActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikaziSmenaFormu();
    }//GEN-LAST:event_menuItemPrikaziSmeneActionPerformed

    private void menuItemPrikaziProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikaziProdavacActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikazProdavcaFormu();
    }//GEN-LAST:event_menuItemPrikaziProdavacActionPerformed

    private void menuItemKreirajProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKreirajProdavacActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajProdavcaFormu();
    }//GEN-LAST:event_menuItemKreirajProdavacActionPerformed

    private void menuItemPrikaziRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikaziRacunActionPerformed
        cordinator.Cordinator.getInstance().otvoriPrikaziRacunFormu();
    }//GEN-LAST:event_menuItemPrikaziRacunActionPerformed

    private void menuItemKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKreirajRacunActionPerformed
        cordinator.Cordinator.getInstance().otvoriKreirajRacunFromu();
    }//GEN-LAST:event_menuItemKreirajRacunActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProdavac;
    private javax.swing.JMenuItem menuItemKorisnikKreiraj;
    private javax.swing.JMenuItem menuItemKreirajMesto;
    private javax.swing.JMenuItem menuItemKreirajProdavac;
    private javax.swing.JMenuItem menuItemKreirajRacun;
    private javax.swing.JMenuItem menuItemKrerirajKartPredstava;
    private javax.swing.JMenuItem menuItemPrikaziKarty;
    private javax.swing.JMenuItem menuItemPrikaziKorisnik;
    private javax.swing.JMenuItem menuItemPrikaziMesta;
    private javax.swing.JMenuItem menuItemPrikaziProdavac;
    private javax.swing.JMenuItem menuItemPrikaziRacun;
    private javax.swing.JMenuItem menuItemPrikaziSmene;
    private javax.swing.JMenuItem menuItemUbaciSmena;
    private javax.swing.JMenu menuKartaPredstave;
    private javax.swing.JMenu menuKorisni;
    private javax.swing.JMenu menuMesto;
    private javax.swing.JMenu menuProdavac;
    private javax.swing.JMenu menuRacun;
    private javax.swing.JMenu menuSmena;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public javax.swing.JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(javax.swing.JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JLabel getLblProdavac() {
        return lblProdavac;
    }

    public void setLblProdavac(javax.swing.JLabel lblProdavac) {
        this.lblProdavac = lblProdavac;
    }

    public javax.swing.JMenuItem getMenuItemKorisnikKreiraj() {
        return menuItemKorisnikKreiraj;
    }

    public void setMenuItemKorisnikKreiraj(javax.swing.JMenuItem menuItemKorisnikKreiraj) {
        this.menuItemKorisnikKreiraj = menuItemKorisnikKreiraj;
    }

    public javax.swing.JMenuItem getMenuItemKrerirajKartPredstava() {
        return menuItemKrerirajKartPredstava;
    }

    public void setMenuItemKrerirajKartPredstava(javax.swing.JMenuItem menuItemKrerirajKartPredstava) {
        this.menuItemKrerirajKartPredstava = menuItemKrerirajKartPredstava;
    }

    public javax.swing.JMenuItem getMenuItemPrikaziKarty() {
        return menuItemPrikaziKarty;
    }

    public void setMenuItemPrikaziKarty(javax.swing.JMenuItem menuItemPrikaziKarty) {
        this.menuItemPrikaziKarty = menuItemPrikaziKarty;
    }

    public javax.swing.JMenuItem getMenuItemPrikaziKorisnik() {
        return menuItemPrikaziKorisnik;
    }

    public void setMenuItemPrikaziKorisnik(javax.swing.JMenuItem menuItemPrikaziKorisnik) {
        this.menuItemPrikaziKorisnik = menuItemPrikaziKorisnik;
    }

    public javax.swing.JMenu getMenuKartaPredstave() {
        return menuKartaPredstave;
    }

    public void setMenuKartaPredstave(javax.swing.JMenu menuKartaPredstave) {
        this.menuKartaPredstave = menuKartaPredstave;
    }

    public javax.swing.JMenu getMenuKorisni() {
        return menuKorisni;
    }

    public void setMenuKorisni(javax.swing.JMenu menuKorisni) {
        this.menuKorisni = menuKorisni;
    }

    public javax.swing.JMenu getMenuProdavac() {
        return menuProdavac;
    }

    public void setMenuProdavac(javax.swing.JMenu menuProdavac) {
        this.menuProdavac = menuProdavac;
    }
}
